language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna@2.0.0 lerna-semantic-release

build:
  - npm run build

deploy:
  provider: script
  script:
    lerna-semantic-release pre
    lerna-semantic-release perform
    lerna-semantic-release post