language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna

build:
  - npm run build

before_deploy:
  - git checkout master
  
deploy:
  provider: script
  skip_cleanup: true
  script:
    lerna publish --repo-version=1.0.0 --yes
    # lerna-semantic-release pre
    # lerna-semantic-release perform
    # lerna-semantic-release post