language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

build:
  - yarn build

deploy:
  provider: script
  script:
    lerna-semantic-release pre
    lerna-semantic-release perform
    lerna-semantic-release post