language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna

build:
  - npm run build

before_deploy:
  - git checkout master
  - git remote set-url origin "https://$GH_TOKEN@github.com/opllama2/op-lib.git"
  - echo "IAM:"
  - npm whoami
  
deploy:
  provider: script
  skip_cleanup: true
  script:
    lerna publish --yes