language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna@2.0.0 lerna-semantic-release

build:
  - git checkout master
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script:
    lerna publish --repo-version=1.0.0 --yes
    # lerna-semantic-release pre
    # lerna-semantic-release perform
    # lerna-semantic-release post