language: node_js
node_js:
  - node

before_install:
  - npm install -g lerna

build:
  - npm run build

before_deploy:
  - git checkout master
  - git remote set-url origin "https://opllama2:$GH_TOKEN@github.com/op-lib.git"
  
deploy:
  provider: script
  skip_cleanup: true
  script:
    lerna publish --repo-version=1.0.0 --yes